/*
 * GS1 Barcode Syntax Dictionary. Copyright (c) 2022-2024 GS1 AISBL.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/**
 * @file lint_cset39.c
 *
 * @brief The `cset39` linter ensures that the given data contains only
 * characters within GS1 AI encodable character set 39 ("CSET 39").
 *
 * @remark CSET 39 is defined in the [GS1 General
 * Specifications](https://www.gs1.org/genspecs) table "GS1 AI encodable
 * character set 39".
 *
 */

#include <assert.h>
#include <string.h>

#include "gs1syntaxdictionary.h"
#include "gs1syntaxdictionary-utils.h"


/**
 * Used to validate that an AI component conforms to `C..99` syntax.
 *
 * Note: The length of the component is validated by the framework that calls
 * this function.
 *
 * @param [in] data Pointer to the null-terminated data to be linted. Must not
 *                  be `NULL`.
 * @param [out] err_pos To facilitate error highlighting, the start position of
 *                      the bad data is written to this pointer, if not `NULL`.
 * @param [out] err_len The length of the bad data is written to this pointer, if
 *                      not `NULL`.
 *
 * @return #GS1_LINTER_OK if okay.
 * @return #GS1_LINTER_INVALID_CSET39_CHARACTER if the data contains a
 *         non-CSET 39 character.
 *
 */
GS1_SYNTAX_DICTIONARY_API gs1_lint_err_t gs1_lint_cset39(const char* const data, size_t* const err_pos, size_t* const err_len)
{

	/*
	 * CSET 39 characters: #-/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
	 *
	 */
	static const uint64_t cset39_bitfield[] = {
		0x000000001005ffc0,		// "#", "-", "/", 0-9
		0x7fffffe000000000,		// A-Z
		0x0000000000000000,
		0x0000000000000000
	};

	size_t pos;

	assert(data);

	/*
	 * Validate character set using bitfield lookup
	 *
	 */
	for (pos = 0; data[pos] != '\0'; pos++) {
		int valid = 0;
		GS1_LINTER_BITFIELD_LOOKUP((unsigned char)data[pos], cset39_bitfield);
		if (GS1_LINTER_UNLIKELY(!valid))
			GS1_LINTER_RETURN_ERROR(
				GS1_LINTER_INVALID_CSET39_CHARACTER,
				pos,
				1
			);
	}

	GS1_LINTER_RETURN_OK;

}


#ifdef UNIT_TESTS

#include "unittest.h"

void test_lint_cset39(void)
{

	UNIT_TEST_PASS(gs1_lint_cset39, "");
	UNIT_TEST_PASS(gs1_lint_cset39, "#-/0123456789ABCDEFG");
	UNIT_TEST_PASS(gs1_lint_cset39, "HIJKLMNOPQRSTUVWXYZ");

	UNIT_TEST_FAIL(gs1_lint_cset39, "ABC_", GS1_LINTER_INVALID_CSET39_CHARACTER, "ABC*_*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "AB_C", GS1_LINTER_INVALID_CSET39_CHARACTER, "AB*_*C");
	UNIT_TEST_FAIL(gs1_lint_cset39, "_ABC", GS1_LINTER_INVALID_CSET39_CHARACTER, "*_*ABC");

	UNIT_TEST_FAIL(gs1_lint_cset39, "\x01", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x01*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x02", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x02*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x03", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x03*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x04", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x04*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x05", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x05*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x06", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x06*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x07", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x07*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x08", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x08*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x09", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x09*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x0A", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x0A*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x0B", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x0B*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x0C", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x0C*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x0D", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x0D*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x0E", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x0E*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x0F", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x0F*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x10", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x10*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x11", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x11*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x12", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x12*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x13", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x13*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x14", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x14*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x15", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x15*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x16", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x16*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x17", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x17*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x18", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x18*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x19", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x19*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x1A", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x1A*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x1B", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x1B*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x1C", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x1C*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x1D", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x1D*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x1E", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x1E*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x1F", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x1F*");
	UNIT_TEST_FAIL(gs1_lint_cset39, " ",    GS1_LINTER_INVALID_CSET39_CHARACTER, "* *");
	UNIT_TEST_FAIL(gs1_lint_cset39, "!",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*!*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\"",   GS1_LINTER_INVALID_CSET39_CHARACTER, "*\"*");
	UNIT_TEST_PASS(gs1_lint_cset39, "#");
	UNIT_TEST_FAIL(gs1_lint_cset39, "$",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*$*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "%",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*%*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "&",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*&*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "'",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*'*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "(",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*(*");
	UNIT_TEST_FAIL(gs1_lint_cset39, ")",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*)*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "*",    GS1_LINTER_INVALID_CSET39_CHARACTER, "***");
	UNIT_TEST_FAIL(gs1_lint_cset39, "+",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*+*");
	UNIT_TEST_FAIL(gs1_lint_cset39, ",",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*,*");
	UNIT_TEST_PASS(gs1_lint_cset39, "-");
	UNIT_TEST_FAIL(gs1_lint_cset39, ".",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*.*");
	UNIT_TEST_PASS(gs1_lint_cset39, "/");
	UNIT_TEST_PASS(gs1_lint_cset39, "0");
	UNIT_TEST_PASS(gs1_lint_cset39, "1");
	UNIT_TEST_PASS(gs1_lint_cset39, "2");
	UNIT_TEST_PASS(gs1_lint_cset39, "3");
	UNIT_TEST_PASS(gs1_lint_cset39, "4");
	UNIT_TEST_PASS(gs1_lint_cset39, "5");
	UNIT_TEST_PASS(gs1_lint_cset39, "6");
	UNIT_TEST_PASS(gs1_lint_cset39, "7");
	UNIT_TEST_PASS(gs1_lint_cset39, "8");
	UNIT_TEST_PASS(gs1_lint_cset39, "9");
	UNIT_TEST_FAIL(gs1_lint_cset39, ":",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*:*");
	UNIT_TEST_FAIL(gs1_lint_cset39, ";",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*;*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "<",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*<*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "=",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*=*");
	UNIT_TEST_FAIL(gs1_lint_cset39, ">",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*>*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "?",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*?*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "@",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*@*");
	UNIT_TEST_PASS(gs1_lint_cset39, "A");
	UNIT_TEST_PASS(gs1_lint_cset39, "B");
	UNIT_TEST_PASS(gs1_lint_cset39, "C");
	UNIT_TEST_PASS(gs1_lint_cset39, "D");
	UNIT_TEST_PASS(gs1_lint_cset39, "E");
	UNIT_TEST_PASS(gs1_lint_cset39, "F");
	UNIT_TEST_PASS(gs1_lint_cset39, "G");
	UNIT_TEST_PASS(gs1_lint_cset39, "H");
	UNIT_TEST_PASS(gs1_lint_cset39, "I");
	UNIT_TEST_PASS(gs1_lint_cset39, "J");
	UNIT_TEST_PASS(gs1_lint_cset39, "K");
	UNIT_TEST_PASS(gs1_lint_cset39, "L");
	UNIT_TEST_PASS(gs1_lint_cset39, "M");
	UNIT_TEST_PASS(gs1_lint_cset39, "N");
	UNIT_TEST_PASS(gs1_lint_cset39, "O");
	UNIT_TEST_PASS(gs1_lint_cset39, "P");
	UNIT_TEST_PASS(gs1_lint_cset39, "Q");
	UNIT_TEST_PASS(gs1_lint_cset39, "R");
	UNIT_TEST_PASS(gs1_lint_cset39, "S");
	UNIT_TEST_PASS(gs1_lint_cset39, "T");
	UNIT_TEST_PASS(gs1_lint_cset39, "U");
	UNIT_TEST_PASS(gs1_lint_cset39, "V");
	UNIT_TEST_PASS(gs1_lint_cset39, "W");
	UNIT_TEST_PASS(gs1_lint_cset39, "X");
	UNIT_TEST_PASS(gs1_lint_cset39, "Y");
	UNIT_TEST_PASS(gs1_lint_cset39, "Z");
	UNIT_TEST_FAIL(gs1_lint_cset39, "[",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*[*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\\",   GS1_LINTER_INVALID_CSET39_CHARACTER, "*\\*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "]",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*]*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "^",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*^*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "_",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*_*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "`",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*`*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "a",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*a*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "b",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*b*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "c",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*c*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "d",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*d*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "e",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*e*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "f",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*f*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "g",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*g*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "h",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*h*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "i",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*i*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "j",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*j*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "k",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*k*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "l",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*l*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "m",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*m*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "n",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*n*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "o",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*o*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "p",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*p*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "q",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*q*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "r",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*r*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "s",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*s*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "t",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*t*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "u",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*u*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "v",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*v*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "w",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*w*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "x",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*x*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "y",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*y*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "z",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*z*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "{",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*{*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "|",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*|*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "}",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*}*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "~",    GS1_LINTER_INVALID_CSET39_CHARACTER, "*~*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x7F", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x7F*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x80", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x80*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x81", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x81*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x82", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x82*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x83", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x83*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x84", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x84*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x85", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x85*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x86", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x86*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x87", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x87*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x88", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x88*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x89", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x89*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x8A", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x8A*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x8B", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x8B*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x8C", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x8C*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x8D", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x8D*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x8E", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x8E*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x8F", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x8F*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x90", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x90*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x91", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x91*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x92", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x92*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x93", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x93*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x94", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x94*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x95", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x95*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x96", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x96*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x97", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x97*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x98", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x98*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x99", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x99*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x9A", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x9A*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x9B", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x9B*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x9C", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x9C*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x9D", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x9D*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x9E", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x9E*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\x9F", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\x9F*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA0", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA0*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA1", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA1*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA2", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA2*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA3", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA3*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA4", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA4*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA5", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA5*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA6", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA6*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA7", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA7*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA8", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA8*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xA9", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xA9*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xAA", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xAA*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xAB", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xAB*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xAC", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xAC*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xAD", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xAD*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xAE", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xAE*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xAF", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xAF*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB0", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB0*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB1", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB1*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB2", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB2*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB3", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB3*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB4", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB4*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB5", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB5*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB6", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB6*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB7", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB7*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB8", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB8*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xB9", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xB9*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xBA", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xBA*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xBB", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xBB*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xBC", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xBC*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xBD", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xBD*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xBE", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xBE*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xBF", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xBF*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC0", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC0*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC1", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC1*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC2", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC2*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC3", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC3*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC4", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC4*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC5", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC5*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC6", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC6*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC7", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC7*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC8", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC8*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xC9", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xC9*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xCA", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xCA*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xCB", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xCB*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xCC", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xCC*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xCD", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xCD*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xCE", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xCE*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xCF", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xCF*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD0", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD0*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD1", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD1*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD2", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD2*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD3", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD3*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD4", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD4*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD5", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD5*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD6", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD6*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD7", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD7*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD8", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD8*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xD9", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xD9*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xDA", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xDA*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xDB", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xDB*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xDC", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xDC*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xDD", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xDD*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xDE", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xDE*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xDF", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xDF*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE0", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE0*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE1", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE1*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE2", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE2*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE3", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE3*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE4", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE4*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE5", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE5*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE6", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE6*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE7", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE7*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE8", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE8*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xE9", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xE9*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xEA", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xEA*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xEB", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xEB*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xEC", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xEC*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xED", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xED*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xEE", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xEE*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xEF", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xEF*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF0", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF0*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF1", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF1*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF2", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF2*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF3", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF3*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF4", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF4*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF5", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF5*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF6", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF6*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF7", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF7*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF8", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF8*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xF9", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xF9*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xFA", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xFA*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xFB", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xFB*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xFC", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xFC*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xFD", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xFD*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xFE", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xFE*");
	UNIT_TEST_FAIL(gs1_lint_cset39, "\xFF", GS1_LINTER_INVALID_CSET39_CHARACTER, "*\xFF*");

}

#endif  /* UNIT_TESTS */
